FROM python:3.12-slim
RUN pip install --no-cache-dir poetry
WORKDIR /app
COPY  poetry.lock pyproject.toml ./
RUN poetry install --no-root --no-interaction

COPY . .
CMD ["poetry", "run", "python", "docker_example.py"]